trigger:
- none

variables:
# - group: IAC_<projectCode>_GLOBAL_VAR_GRP
- group: AGENT_POOL_VAR_GRP

- name: resourceGroup
  value: azu-lndvops01   #azu-lnadoresd01                #azu-lndevopsd01 (commented values are for sandbox)
  readonly: true

- name: subscriptionId
  value: 1971f0d2-b061-4971-bbee-56171d168156  #bab871b9-ac22-460b-919a-d51ea040aef3 (dev)
  readonly: true

pool: 
  vmimage: ubuntu-latest

parameters:
## TODO: Refer all branches from "release" branch only.
  - name: templateBranch
    displayName: Template Repo Branch Name
    type: string
    default: release
  
  - name: iacModulesBranch
    displayName: IaC Modules Branch Name
    type: string
    default: release

  - name: moduleName
    displayName: Name of the bicep module to test
    type: string
    values:
    - storageAccount
  
  # - name: env
  #   displayName: Enviroment to deploy to
  #   type: string


resources:
  repositories:
    - repository: CI_CD_Templates
      endpoint: LennarGitHubServiceConnection
      ref: refs/heads/${{ parameters.templateBranch }}
      type: github
      name: devsecops-len/ci-cd-templates

    - repository: iacModules
      endpoint: LennarGitHubServiceConnection
      ref: refs/heads/${{ parameters.iacModulesBranch }}
      type: github
      name: devsecops-len/iac-modules


stages:
  - template: cd-templates/bicep-deployment-template/v1.1/bicep-deployment-template.yaml@CI_CD_Templates   # cd-templates/what-if-bicep-deployment-template/v1.1/what-if-bicep-deployment-template.yaml@CI_CD_Templates   
    parameters:
      resourceGroup: $(resourceGroup)
      subscriptionId: $(subscriptionId)
      csmFile: corp-devops-deployment-config/infra-as-code/bicep/main2.bicep
      parameterFile: corp-devops-deployment-config/infra-as-code/bicep/sandbox01/baseline-infra/parameters-sandbox2.bicepparam
      # env: ${{parameters.env}}
